### ISSUE TITLE
onKeyDown and tabbing through elements conflict

### ISSUE THREAD

**Issue by tmns** [karlhadwen/todoist#11]
Hi @karlhadwen, in the tutorial you tend to use the `onKeyDown` event handler for the usage of keys to interact with the app. However, in my experience this led to confusing behavior, as I would press the `tab` key to move on to the next element but instead of moving on to the next element it would toggle whatever element I was on. For example, if I was on the pizza / dark mode element, it would toggle dark mode instead of tabbing to the next element.

I imagine this isn't desired behavior? Or am I missing something?

While following along myself, I simply used `onKeyPress` and matched on the `Enter` key, like so:

```js
onKeyPress={e => {
  if (e.key === 'Enter') {
    setDarkMode(!darkMode);
  }
}}
```

That way I could still tab through elements as expected and then only toggle them when I wanted to with the `Enter` key. Let me know if I'm thinking about this incorrectly!

**Comment by karlhadwen** [comment]
Hey dude, sorry I’ve only just seen this! Could you please put a PR up if possible as I’d enjoy this experience more than what I did? Thanks!

**Comment by karlhadwen** [comment]
Thanks to @LucasShaffer this is now implemented!
