### ISSUE TITLE
when i run npm start appear some question, what can do to resolve this question

### ISSUE THREAD

**Issue by zhengquantao** [karlhadwen/todoist#12]
./src/components/AddTask.js
Module not found: Can't resolve '../firebase' in '/home/zhengquantao/python/FaceTest/todoist/src/components'

**Comment by karlhadwen** [comment]
That's an odd one, did you clone the repo correctly?

**Comment by robthedev** [comment]
@zhengquantao Use import { firebase } from '../firebase.prod';
