### ISSUE TITLE
in project not showing options 

### ISSUE THREAD

**Issue by jzebgul** [karlhadwen/todoist#17]
![Screen Shot 2020-05-18 at 1 40 13 AM](https://user-images.githubusercontent.com/60641774/82159594-c6797e00-98a8-11ea-8c46-145a7ac94948.png)

**Comment by karlhadwen** [comment]
Need more information, have you created projects in Firebase? Are you using the same create-react-app version?

**Comment by jzebgul** [comment]
mybe not but i started creating from scratch a new toodo

**Comment by karlhadwen** [comment]
Please join the Discord for further help: https://t.co/C1bSu5avWw?amp=1
