### ISSUE TITLE
No firebase module?

### ISSUE THREAD

**Issue by dboland77** [karlhadwen/todoist#22]
Hello,
On the youtube tutorial and when you run this it looks for firebase.js ... this does not seem to exist?

**Comment by karlhadwen** [comment]
Hi, I took it out as it had my details in there, but all you have to do is create the file and drop your details in there and it should work.

**Comment by dboland77** [comment]
Thanks for getting back to me - makes sense.

I got this setup and it works perfectly it's a great tutorial and resource so thank you for creating this and the YouTube code along.
