### ISSUE TITLE
Lack of file

### ISSUE THREAD

**Issue by SomeYearSomeMonth** [karlhadwen/todoist#3]
./src/components/AddProject.js
Module not found: Can't resolve '../firebase' in 'E:\todoist-master\src\components'

**Comment by ajmhyd** [comment]
@SomeYearSomeMonth You need to create a ``firebase.js`` file. It looks like this but with your own firebase information.
 ```javascript
import firebase from 'firebase/app';
import 'firebase/firestore';

const firebaseConfig = firebase.initializeApp({
  apiKey: '',
  authDomain: '',
  databaseURL: '',
  projectId: '',
  storageBucket: '',
  messagingSenderId: '',
  appId: '',
});

export { firebaseConfig as firebase };
```

**Comment by karlhadwen** [comment]
Yep, exactly what @ajmhyd said, just rename `firebase.prod.js` to be `firebase.js`, I'll push a change now for this.
