### ISSUE TITLE
a little confused about setproject hooks code

### ISSUE THREAD

**Issue by apawn** [karlhadwen/todoist#4]
Hi 

i got little confused about the follow code 
```
export const useProjects = () => {
  const [projects, setProjects] = useState([]);

  useEffect(() => {
    firebase
      .firestore()
      .collection('projects')
      .where('userId', '==', 'jlIFXIwyAL3tzHMtzRbw')
      .orderBy('projectId')
      .get()
      .then(snapshot => {
        const allProjects = snapshot.docs.map(project => ({
          ...project.data(),
          docId: project.id,
        }));

        if (JSON.stringify(allProjects) !== JSON.stringify(projects)) {
          setProjects(allProjects);
        }
      });
  }, [projects]);

  return { projects, setProjects };
};
```

i thought, if component calls setProject, the hooks will update projects, and the UI will got updated.
after that, the effect will got fired, which will update the UI again.

should that reading from firebase just get called in app mounting time, and when component calls setProject, we just need to save it to firebase.

sorry for the poor english, the about maybe seems a little rude, but i am not meaning it

**Comment by karlhadwen** [comment]
Hey @apawn, so what happens here is that when `useProjects` is called, it goes ahead and makes a request to Firebase to get the data. If `projects` changes, it will re-run the `useEffect` so that's why I've added a `JSON.stringify` in there, so make sure it doesn't go into an infinite loop. If you call `setProjects` it will go ahead call Firebase again. Hopefully, that makes sense, if not let me know and I'll try my best to help :)

**Comment by blacksonic** [comment]
I also got confused here. Is it necessary to use `.get` and `.onSnapshot` also?
Handling Firebase like a Rest API, and maintaining a local state ignoring live changes would clarify it a lot.

**Comment by karlhadwen** [comment]
@blacksonic For this particular hook it does ignore live changes and just gets you a `snapshot` of what you have in the database.

**Comment by apawn** [comment]
@karlhadwen i mean here, it is not necessary to subscribe to the changes of firebase,  we just use it for storage. and when calling useProject, you can save the data to firebase, and after that, update the state, which will cause UI  update. when first time mounting the App Component, reading data from firebase.

**Comment by karlhadwen** [comment]
@apawn you will see that it's not actually updating to firebase or subscribing listening to events, it takes a snapshot, unlike the tasks that are subscribing and listening for changes in tasks.

**Comment by vp5h** [comment]
I am using the same code, Something is still wrong out there,  It was triggering requests to firebase without even me changing a thing on ui, When i remove project from dependecy array, The rerender stoped and I only got a new project, when I refresh the app,I could be wrong, I feel like this   if (JSON.stringify(allProjects) !== JSON.stringify(projects))  condition is always truthy and thats casuing the whole rerender thing, I could be wrong, Thanks for reading.

**Comment by vp5h** [comment]
Something is causing it to render projects again and again is there a possibility of circular dependency here

**Comment by vp5h** [comment]
```
const allProjects = snapshot.docs.map((project) => ({
          name: project.data().name,
          userId: project.data().userId,
          projectId: project.data().projectId,
          docId: project.id,
        }));

```

This solves the RErendering as  Stringify conditions work only when sequence is maintained, firestore is Sending data in random order at times, So avoid spread operaetor here would save 50k firebase calls for you.
